"""empty message

Revision ID: bb21838e5e8e
Revises: 
Create Date: 2022-03-03 19:35:09.462835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb21838e5e8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.LargeBinary(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('data_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requesting_user', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('requested_url', sa.String(length=256), nullable=False),
    sa.Column('expected_dimensionality', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['requesting_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('data_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request', sa.Integer(), nullable=False),
    sa.Column('data', sa.PickleType(), nullable=False),
    sa.ForeignKeyConstraint(['request'], ['data_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dropped_client_secret_shares',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('secret_of_dropped_device', sa.Integer(), nullable=False),
    sa.Column('secret_with_device', sa.Integer(), nullable=False),
    sa.Column('share_id', sa.Integer(), nullable=False),
    sa.Column('decrypted_share', sa.PickleType(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['data_requests.id'], ),
    sa.PrimaryKeyConstraint('request_id', 'secret_of_dropped_device', 'secret_with_device', 'share_id')
    )
    op.create_table('participating_device_secret_shares',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_for_device', sa.Integer(), nullable=False),
    sa.Column('secret_of_dropped_device', sa.Integer(), nullable=False),
    sa.Column('secret_with_device', sa.Integer(), nullable=False),
    sa.Column('share_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_share', sa.PickleType(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['data_requests.id'], ),
    sa.PrimaryKeyConstraint('request_id', 'encrypted_for_device', 'secret_of_dropped_device', 'secret_with_device')
    )
    op.create_table('participating_devices',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.String(), nullable=False),
    sa.Column('diffie_hellmann_public_component', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['data_requests.id'], ),
    sa.PrimaryKeyConstraint('request_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participating_devices')
    op.drop_table('participating_device_secret_shares')
    op.drop_table('dropped_client_secret_shares')
    op.drop_table('data_responses')
    op.drop_table('roles')
    op.drop_table('data_requests')
    op.drop_table('users')
    # ### end Alembic commands ###
